name: build-osuassist

on:
  push:
    branches:
      - main
    paths:
      - 'osuassist/**'
      - 'imgui/**'
      - 'include/**'
  workflow_dispatch:
    branches:
      - main
    paths:
      - 'osuassist/**'
      - 'imgui/**'
      - 'include/**'

jobs:
  windows-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Visual Studio Environment
        uses: Ciremun/gha-setup-vsdevenv@avoid-deprecation-warnings
        with:
          arch: 'x86'

      - name: Build Project
        shell: cmd
        run: |
          cl nobuild.c && nobuild.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: osuassist
          path: |
            osuassist_injector.exe
            osuassist.dll
            config.ini
